### ISSUE TITLE
purgecss-webpack-plugin清除了有用的css

### ISSUE THREAD

**Issue by fancyluo88** [imguolao/webpack4-demo#1]
使用create-react-app+ 按需加载antd 然后配置purgecss-webpack-plugin 发现好多antd的样式没有打包进来，有遇到过吗？
const PATHS = {
  src: path.join(__dirname, 'src')
}
const purgecssPlugin = new PurgecssPlugin({
  paths: glob.sync([
    `${PATHS.src}/**/*`,
    `${__dirname}/public/index.html`,
  ], {
    // 不匹配目录，只匹配文件
    nodir: true,
  })
});

**Comment by imguolao** [comment]
很抱歉，我现在才看到这个 issues.
解决办法我已经上传到demo_5，README 也更新了说明，或者你直接前往 [purgecss-webpack-plugin/issues/25](https://github.com/FullHuman/purgecss-webpack-plugin/issues/25) 查看解决办法也可以。
